setw -g mouse on
set-option -g focus-events on

set -g default-terminal 'tmux-256color'
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# copy + paste to system clipboard
unbind -T copy-mode-vi Space; #Default for begin-selection
unbind -T copy-mode-vi Enter; #Default for copy-selection

# Fix Vim ESC delay (tmux 3.5+ already defaults to 10ms)
set -sg escape-time 1

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel --clipboard"

if-shell -b 'test -n "$WSLENV"' 'bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel clip.exe'
if-shell -b 'test -n "$WSLENV"' 'bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel clip.exe'

# statusbar colors
set -g status-position top
set -g status-style 'fg=brightwhite, bg=brightblack'
set -g status-left-length 150
set -g status-right-length 150

# default window title
setw -g window-status-current-format '▐#[fg=black]#[bg=brightwhite] #I#F #W #[default]▌'
